


spring:
  datasource:
    url: jdbc:sqlserver://ms1901.gabiadb.com:1433;databaseName=speedmiscom
    username: speedmiscom
    password: djajsk!!00fw



  devtools:
    livereload:
      enabled: true


server:
  port : 8081
